### PR TITLE
add react todomvc example

### PR DESCRIPTION
**Pull request by lapanoid**
Still have https://github.com/lahmatiy/component-inspector/issues/9
It would be much easier to find out what is happening if we will have same environment, I think component-inspector should have some examples anyway
So I made this PR with react todomvc example

### CODE REVIEW

**Comment by lahmatiy** [comment]
Cool! Thank you!

**Comment by lahmatiy** [comment]
One question: is it `.babelrc` file needed? I thought all babel settings are in webpack config.

**Comment by lapanoid** [comment]
webpack search for this file and get's settings from it if it exists

**Comment by lapanoid** [comment]
Could you troubleshoot #9 on this example, everything works for you? @lahmatiy

**Comment by lahmatiy** [comment]
> webpack search for this file and get's settings from it if it exists

But all settings could be set in webpack config. This file doesn't needed than.

> Could you troubleshoot #9

It's ok to me. I'm awaiting you close it.

**Comment by lapanoid** [comment]
> But all settings could be set in webpack config. This file doesn't needed than.
You can do that, it is only a matter of preferences.
> Can't close it as I still have the issue. 
No, I can't as still have this issue. Can I build not minified lib somehow with basis to add some logs and test this?

**Comment by lahmatiy** [comment]
Let's have a conversation in proper place? Here: #9

**Pull request merged**
